Remove the json parse for inputs parameter
googleapis/nodejs-automl pull request #582
Opened 2022-01-13 15:49 UTC by danieljbruce

This fixes an issue where if a particular line is uncommented and used then an error is thrown on the `JSON.parse(inputs)` line.

Fixes #581

2022-01-13 17:17 UTC, bcoe requested changes
I would instead move the parse step to above:

```
// [START automl_tables_predict]
```

The reason that the input is a `string` is so that you can pass it in from command line.

Then, in a commented out line, just do:

```
// const inputs = [{numberValue: 1}...]
```

2022-01-13 17:18 UTC, bcoe commented
(the START/END blocks are what will show up in embeded documentation).

2022-01-13 18:41 UTC, danieljbruce commented
Sounds like a good plan. Thanks for the context regarding START and END blocks.

2022-01-13 19:24 UTC, bcoe approved these changes

2022-01-17 19:39 UTC, bcoe approved these changes

2022-01-25 16:53 UTC, merged